### ISSUE TITLE
Invalid model causes template list to be empty

### ISSUE THREAD

**Issue by kullervo16** [kullervo16/checklist#35]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
963		at kullervo16.checklist.model.Step.<init>(Step.java:107)
964		at kullervo16.checklist.model.persist.TemplatePersister.handleData(TemplatePersister.java:81)
965		at kullervo16.checklist.model.persist.TemplatePersister.checkAndLoadDataFromFile(TemplatePersister.java:57)
966		at kullervo16.checklist.model.Template.checkAndLoadDataFromFile(Template.java:89)
967		at kullervo16.checklist.model.Template.getDescription(Template.java:68)
968		at kullervo16.checklist.repository.TemplateRepository.getTemplateInformation(TemplateRepository.java:95)
969		at kullervo16.checklist.rest.TemplateService.listTemplateNames(TemplateService.java:56)

**Comment by kullervo16** [comment]
[deployment-v3.zip](https://github.com/kullervo16/checklist/files/412634/deployment-v3.zip)
